### ISSUE TITLE
Deletes also FavIcon

### ISSUE THREAD

**Issue by alst-ovh** [ghostboard/ghost-purge-images#12]
Deletes the Publication icon (favIcon) ?

**Comment by dburgos** [comment]
No, the favicon is located at the theme folder (`content/themes/<yourtheme>/assets`) and this app checks only the uploaded files, located on `content/images`

Feel free to check the code at [ghost-purge-images/lib/ghost/uploads.js](https://github.com/ghostboard/ghost-purge-images/blob/master/lib/ghost/uploads.js)
