### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by WatsonJH** [ghostboard/ghost-purge-images#15]
Hi :)

I generated my API keys but I get the following error: _`❌ Error: Error: connect ETIMEDOUT MyServerIPAddress:443`_

Thx

**Comment by WatsonJH** [comment]
I tried with Ghost in Private and Public mode, but same results...

**Comment by dburgos** [comment]
Hi

Looks like a connectivity issue,  this tool is using the `url` value at your `ghost/config.production.json` feel free to check it

You don't have to provide the port (like `:443` you provided) or the IP.
Just use the public URL (like `https://example.com/blog`, `https://myblog.com`, `http://blog.example.com` or similar) like you visit via browser

Hope this helps, let me know any question :)

**Comment by sedago** [comment]
My config (inside docker) has the following values:

  "url": "http://localhost:2368",
  "server": {
    "port": 2368,
    "host": "::"
  },


But when I run the command, I get the following error:
❌ Error: Error: connect ETIMEDOUT MY_PUBLIC_IP:443

The URL command seems to be ignored, as "--url=http://localhost:2368" returns the identical error.
