### ISSUE TITLE
Make it works with Docker based intallation

### ISSUE THREAD

**Issue by MoryCorp** [ghostboard/ghost-purge-images#16]
Hi, whenever I try to make the script works with my docker installation I got an error :

Error reading config.production.json Error: Cannot find module config.production.json
So I tried to BS by creating this file following the official Ghost doc just to indicate the path of my content and then :
Error: TypeError: Cannot read property 'endsWith' of undefined

Have you ever experienced this ?
Thanks

**Comment by F-Node-Karlsruhe** [comment]
I had a smiliar issue: installing the npm package in the docker container works fine but running it throws an error that the api can't be reached

**Comment by buarle** [comment]
same here...

first error happens when located in /content floder
second error happends when located one directory up where "config.production.json" is

**Comment by F-Node-Karlsruhe** [comment]
The authors fetch works fine but I get `❌ Error: API Pages - Not valid response` on the pages. 
The difference is that authors gets called with api version 3 and the others with version 2.

**Comment by F-Node-Karlsruhe** [comment]
After going into the container and changing the url in `config.production.json` to the domain with https it works just fine. As far as I know the ghost api demands https, so leaving the default localhost:2365 does produce an invalid api response.

**Comment by buarle** [comment]
worked perfectly! thanks man!

**Comment by MoryCorp** [comment]
> After going into the container and changing the url in `config.production.json` to the domain with https it works just fine. As far as I know the ghost api demands https, so leaving the default localhost:2365 does produce an invalid api response.

Awesome, thanks for the help

**Comment by dburgos** [comment]
I added the optional parameter `url`, so now you can point the tool to use that URL instead of editing the `config.production.json` file, hope it helps.
[Learn more in the readme](https://github.com/ghostboard/ghost-purge-images#url)
