### ISSUE TITLE
Some images from settings are being deleted when they shouldn't

### ISSUE THREAD

**Issue by Maxszik** [ghostboard/ghost-purge-images#17]
A small issue here:

The following images are being deleted each time I run the script
- Publication icon (_not_ Publication logo)
- Twitter card
- Facebook card

These ones are found in _Settings-General_

It's not that big an issue, as I'm aware of it I just have to re-upload the images again once I've done image-purge. But anyway, it seems like a small bug to me.

**Comment by mesquka** [comment]
+1 can reproduce this

The bug from a previous issue that removes optimised images (ending in _o), the workaround I've been using is to [turn off image optimisation](https://github.com/TryGhost/Ghost/blob/0faf89b5abcf6de747d4b309cdac364a863c71dc/core/server/config/defaults.json#L82).

**Comment by dburgos** [comment]
Thank you @Maxszik @mesquka :)

It's fixed on the [new release 3.0.5](https://www.npmjs.com/package/ghost-purge-images/v/3.0.5)
