### ISSUE TITLE
Support (some) custom storage adaptors

### ISSUE THREAD

**Issue by mesquka** [ghostboard/ghost-purge-images#18]
I've got a fork running to support the s3 adaptor I'm using by [adding in a flag to specify a custom directory](https://github.com/mesquka/ghost-purge-images-customdir/commit/92a4b9d12ca766c8507f5717ea54f374d62c0411) and mounting s3 via fuse. The same approach would seem to work across most storage adaptors. Would be good to see this merged into upstream.

**Comment by dburgos** [comment]
Thanks @mesquka 

I merged this, mentioned you as a contributor and now it's included on [release v3.1.0](https://www.npmjs.com/package/ghost-purge-images)
