### ISSUE TITLE
Delete profile images from unpublished authors

### ISSUE THREAD

**Issue by Luen** [ghostboard/ghost-purge-images#19]
If there are no published posts by an author, then the author's profile and cover photos are deleted. 

I have a draft that ready to be published by a new author. The script deleted their profile and cover iamges.

**Comment by dburgos** [comment]
Thanks @Luen

Due the [Content API](https://ghost.org/docs/api/v3/content/#authors) does not return authors with zero published posts, this tool can not handle this

> Authors that are not associated with a post are not returned. You can supply include=count.posts to retrieve the number of posts associated with an author.

I tried this param but it adds the count for authors with at least 1 post, so no way to get authors with 0 posts.

I [updated the README](https://github.com/ghostboard/ghost-purge-images#-observations) to be clear & list this cases
