### ISSUE TITLE
Images in use are being deleted

### ISSUE THREAD

**Issue by Maxszik** [ghostboard/ghost-purge-images#2]
After purging images I had a sense some images had dissapeared/errors. Then I made an experiment, sort of.

I added images to my ghost site by various means. I uploaded images by clicking on the add image variant, and by simply dropping them. I uploaded to galleries, and I dropped many images at once. I also uploaded images the ghost-markdown-card-way. I did it on published posts, on pages and with drafts.

The results are that images are dissapearing that should have been left alone. It seems very random and I can't see a pattern. Some images have been removed in a random way. the only pattern I might possibly see is that on a few occasions where I dropped a lot (10+) pics on the post at once, all had been purged.

So obviously something here is not working. I'm on the digitalocean droplet-variant, latest ghost.

**Comment by Maxszik** [comment]
Additioonal info, very unsure if it can possibly be related:

Background: I'm one of those with zero experience doing things in terminal/console, ssh and all that.

That means I was fiddling around by trial and error when A trying to install ghost-purge-images, and B trying to execute the purge command. At `root`, doing `cd /var/www/ghost` and all that, and so on. Could this possible have made any difference?

On a side note, I would like to suggest a few more instructions in the readme:
- Where and how (exactly) to install on a droplet, for example.
- Where and how, _exactly_, to execute the purge command. For people like me that would be a great help.

**Comment by dburgos** [comment]
@Caucasus-and-Mercury currently it's already on the README, you can find:
- [How to install ](https://github.com/ghostboard/ghost-purge-images#-install) (it installs globally, don't care the current folder)
- [How to execute it](https://github.com/ghostboard/ghost-purge-images#-execute) in your Ghost folder, where you installed it.
- Both for `display` and `purge` commands, you will see the files list. When `purge`, also at the end if each file was removed or not

Still trying to reproduce the issue

**Comment by Maxszik** [comment]
Well that's kind of what I meant. It only says Run npm install -g ghost-purge-images to install, not explicitly where. As I tried to say, those things aren't that intuitive to some of us. I was also at a loss as to whether I should run the `sudo -i -u ghost-mgr` that Ghost suggests at the beginning, I'm still not sure. I agree the instruction of how to execute is sufficient.

Pls let me know if I could help you reproduce somehow. I now realised that I saved the terminal results after running, would you need it?

**Comment by dburgos** [comment]
@Caucasus-and-Mercury yes, the terminal results may help to debug. After purge the images, did you check any post or page on your blog and detect that any image was removed?

For now, I can reproduce it for draft posts & draft pages, working on a fix

**Comment by dburgos** [comment]
@Caucasus-and-Mercury also please note [Ghost creates optimized images](https://blog.ghost.org/image-galleries/), so when you upload one picture, Ghost creates another one optimized with the same name but adding `_o` at the end. So you can get more images to delete that uploaded.

The issue about deleting **images that are being used in drafts** is fixed in the [latest version 2.1.0](https://github.com/ghostboard/ghost-purge-images/tree/v2.1.0), which requires Ghost +2.16 in order to use [Ghost Admin API](https://docs.ghost.org/api/admin/) to fetch drafts. 

Also the [README](https://github.com/ghostboard/ghost-purge-images) was updated I hope you find it clearer and more useful 🙂 Feedback is welcome
