### ISSUE TITLE
Favicon (Publication Icon)

### ISSUE THREAD

**Issue by rkafp** [ghostboard/ghost-purge-images#20]
**The active favicon image is always detected not used**

👇 Unused images that can be removed:
- /var/www/site/content/images/2020/12/favicon.png (0.03 MB)
- /var/www/site/content/images/2020/12/favicon_o.png (0.05 MB)

📊 Summary:
- 2 files of 17 uploaded images (11.76%)
- Total space: 0.08MB

**Comment by dburgos** [comment]
Thank you @rkafp 

It's fixed on the [new release 3.0.5](https://www.npmjs.com/package/ghost-purge-images/v/3.0.5)
