### ISSUE TITLE
Doesn't work for me...

### ISSUE THREAD

**Issue by Maxszik** [ghostboard/ghost-purge-images#3]
Sorry, still doesn't work for me. I'm following the instructions _very very_ carefully. I'm getting this:

root@ghost-caucasusandmercury:~# cd /var/www/ghost
root@ghost-caucasusandmercury:/var/www/ghost# ghost-purge-images display --content-key=69891a65807dc1931c98406ded --admin-key=5cefed645c7944048554b2d5:b50084fd0cdda8fa7cb93fb2f17c2537cd294aa1f540b3f307ca6dbedc48da8b
🔑 Required parameter CONTENT_KEY is missing!
🔑 Required parameter ADMIN_KEY is missing!
❓ Need a key?
  - On your Ghost admin > Integrations > Create custom integration
  - Copy Content API & Admin API Keys

On a side note, I'm having Ghost-CLI version: 1.9.9 as I'm unable to update it for some reason.

Any idea?

**Comment by dburgos** [comment]
💡 The issue was related about the hyphen `-` in the param names. This is just fixed in **v2.1.1**

@Caucasus-and-Mercury please update to the last version running `npm install -g ghost-purge-images` and try again, thanks for your patience!
