### ISSUE TITLE
Does ghost-purge-images work on ghost v4?

### ISSUE THREAD

**Issue by helpme1** [ghostboard/ghost-purge-images#30]
In readme, I did not see mention about ghost v4. Does ghost-purge-images support ghost v4? Does ghost-purge-images support Ubuntu and Windows 10?

**Comment by dburgos** [comment]
Hi @helpme1
- Yes, it is compatible with Ghost v4. I added it in the README
- As long as the parameters and paths are correct, the OS should not affect. 
In Ubuntu/Debian, I can confirm that it is tested and works. 
I have not tested it in Windows 10, let me know if you find any issue
