### ISSUE TITLE
Add the possibility to purge audio and video?

### ISSUE THREAD

**Issue by Maxszik** [ghostboard/ghost-purge-images#31]
Now that Ghost has added the possibility to upload audio, video and other files, it would be terrific if it would be possible to purge those as well.

**Comment by dburgos** [comment]
Hi @Maxszik , thanks for your message

It is added in the just-released v3.2.0 https://www.npmjs.com/package/ghost-purge-images/v/3.2.0

Please let me know if you have any questions or find any issue, happy to help :)

**Comment by Maxszik** [comment]
Terrific, that was very fast, bravo.
Just one question: does this purge files as well. Ghost now supports uploads of video, audio and files/docements. Thank you !

**Comment by dburgos** [comment]
thank you @Maxszik 
no, the v3.2.0 does not support it
I just released v3.2.1 that includes it :)
