### ISSUE TITLE
Ghost v.5

### ISSUE THREAD

**Issue by uPagge** [ghostboard/ghost-purge-images#37]
Thanks for your work
Is Ghost v5 supported?

**Comment by uPagge** [comment]
@dburgos Is this project supported or shouldn't it be used?

**Comment by dburgos** [comment]
Thanks @uPagge yes, Ghost v5 is supported
Sorry for the delay, I thought I already replied to your first message. The project is supported but it's only me :)

I added a versions compatibility table to the README, I hope it's clearer now

Please let me know if you find any issues or have any suggestions

**Comment by uPagge** [comment]
Yes, I’ve already used your solution. It works, thank you very much.

But it also seems that it believes that images of different sizes are not used, although this is not the case. It turns out that it removes images from the /images/size folder. And Ghost then recreates them. It would be great if the script didn’t touch such images. In theory, they can be filtered by the name of the original.

**Comment by dburgos** [comment]
good point @uPagge 
let me reproduce it and update the logic, thank you!

**Comment by uPagge** [comment]
I’ll be looking forward to it. I’m glad the project hasn’t been abandoned. It is not clear why the Ghost main team cannot implement such logic. I literally didn’t use 60% of the images and only took up space in vain.

And one more suggestion. Ghost has the ability to upload files, and apparently there is the same problem. It may make sense to expand the functionality to downloadable files, because they will take up even larger size. Ghost adds files to a separate files folder at the same level as images

**Comment by dburgos** [comment]
hey @uPagge now the `images/size` folder is excluded in the [3.2.4 version](https://www.npmjs.com/package/ghost-purge-images/v/3.2.4) 

thanks again! 🙂

**Comment by uPagge** [comment]
Hmm, but that means that the images won't be deleted from there, but there will be even more garbage?
