### ISSUE TITLE
Ghost 3 support

### ISSUE THREAD

**Issue by remjx** [ghostboard/ghost-purge-images#5]
When I run

```
/var/lib/ghost# ghost-purge-images display --content-key=<myContentKey> --admin-key=<myAdminKey>
```
in Ghost 3.3.0 I get this error: `Error: API Pages - Not valid response`

Can someone confirm Ghost 3 is not supported at the moment? 

cc @dburgos

**Comment by dburgos** [comment]
hey @markjackson02 ,

Previously were using Ghost Content API v2, some minutes ago [ghost-purge-images@v3.0.0](https://www.npmjs.com/package/ghost-purge-images) was released to support v3

Please let me know any issue you may find to help you, thanks

**Comment by remjx** [comment]
Thanks!! I will give it a try and open another ticket if I have any issues.
